# Generated by Django 2.2.2 on 2019-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
